apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
data:
  {{ .Values.configMap.fileName | default "config.yaml" }}: |-
{{ toYaml .Values.configMap.content | indent 4 }}
