apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingressGateway.enabled }}
  gateways:
    - {{ .Values.ingressGateway.name | quote }}
  {{- end }}    
  hosts:
    {{- if .Values.ingressGateway.enabled }}
    - {{ .Values.ingressGateway.host | quote }}
    {{- else }}
    - {{ include "<CHARTNAME>.fullname" . }}{{ (print "." .Release.Namespace ".svc") | quote }}
    {{- end }}
  http:
    - route:
      - destination:
          host: {{ include "<CHARTNAME>.fullname" . }}{{ (print "." .Release.Namespace ".svc") | quote }}
          {{- if .Chart.AppVersion }}
          subset: {{ (print "v" .Chart.AppVersion) | quote }}
          {{- end }}

      {{- if .Values.ingressGateway.enabled }}    
      match:
        {{- range .Values.ingressGateway.matchPrefix }}
        - uri:
            prefix: {{ . | quote }}
        {{- end }}
      {{- end }}
